### ISSUE TITLE
jquery and highcharts not working 

### ISSUE THREAD

**Issue by lumpyspacecoder** [jhuenges/highcharts-demo#3]
TypeError: $(...).highcharts is not a function is the error I am receiving at the statement:

chart = $("#container-chart-reactive").highcharts({ .....})

**Comment by jhuenges** [comment]
Are you getting this error simply by cloning the example? Could you give me a little bit more information (package list and more code)?

**Comment by jhuenges** [comment]
@lumpyspacecoder ?

**Comment by lumpyspacecoder** [comment]
Not by cloning. Please see my example here:
https://github.com/lumpyspacecoder/DataMaps

**Comment by jhuenges** [comment]
~~Okay, I see that you added `maazalik:highcharts` to your package. But I cant find any code related to that package. Can you point me to a specific file?~~

~~EDIT: If there is a bug somewhere you can create a new branch in your project and I can take a look at it~~

I found the code ... silly me! I am looking into it

**Comment by jhuenges** [comment]
Okay, I found the bug:
https://github.com/lumpyspacecoder/DataMaps/blob/master/client/main.html#L6-L8
You cant use scripts like this. Line 6 is useless, because you already have the `jquery` package; The `script.js` in line 7 doesnt exists and cant be used that way; And regarding line 8 - I am sure there is another way to use google maps ([package](https://atmospherejs.com/dburles/google-maps)). 

If you need anymore help, please let me know.

**Comment by lumpyspacecoder** [comment]
Ooh. I totally missed that old code. It works now! Thanks!
